<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageVersion Include="Hexa.NET.ImGui.Backends" Version="1.0.18" />
    <PackageVersion Include="Hexa.NET.ImGui.Backends.SDL3" Version="1.0.18" />
    <PackageVersion Include="Hexa.NET.ImNodes" Version="2.2.9" />
    <PackageVersion Include="Hexa.NET.ImPlot" Version="2.2.9" />
    <PackageVersion Include="Hexa.NET.ImPlot3D" Version="2.2.9" />
    <PackageVersion Include="Hexa.NET.OpenGL3" Version="1.1.0" />
    <PackageVersion Include="Hexa.NET.SDL3" Version="1.2.16" />
    <PackageVersion Include="Sourcy.DotNet" Version="1.1.1" />
    <PackageVersion Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageVersion Include="TedToolkit.RoslynHelper" Version="2026.3.31" />
  </ItemGroup>
</Project>