<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TedToolkit.Hexa.Raii.ImGui\TedToolkit.Hexa.Raii.ImGui.csproj" />
      <ProjectReference Include="..\TedToolkit.Hexa.Raii.ImNodes\TedToolkit.Hexa.Raii.ImNodes.csproj" />
      <ProjectReference Include="..\TedToolkit.Hexa.Raii.ImPlot3D\TedToolkit.Hexa.Raii.ImPlot3D.csproj" />
      <ProjectReference Include="..\TedToolkit.Hexa.Raii.ImPlot\TedToolkit.Hexa.Raii.ImPlot.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Hexa.NET.ImGui.Backends" />
      <PackageReference Include="Hexa.NET.ImGui.Backends.SDL3" />
      <PackageReference Include="Hexa.NET.OpenGL3" />
      <PackageReference Include="Hexa.NET.SDL3" />
    </ItemGroup>

</Project>
